### ISSUE TITLE
File /events/guildCreate

### ISSUE THREAD

**Issue by CatInChair** [Night-Devs/EclipseBot#16]
`if (!guild) return`
Он запускается при запуске на уровне вебсокетов, но до разработчика, использующего discord.js, не доходят события инициализации клиента, в том числе события, инициализирующие гильдии, на которых уже присутствует бот

**Comment by Elektroplayer** [comment]
Эмм, попрошу заглянуть в ветку dev. Такого ивента как бы нет в новой версии, хотя буду знать на всякий случай.
